### ISSUE TITLE
wants to download BeamNG.drive? 

### ISSUE THREAD

**Issue by 3k2** [v0l/void.cat#16]
Hi

I made dummy file at windows using fsutil file createnew c:\users\steve\desktop\5gb.bin 5368709120

then I uploaded it to void.cat using sharex. 
![image](https://user-images.githubusercontent.com/11908261/42413933-d135979e-8233-11e8-8e11-b957612ef91c.png)

download says:

![image](https://user-images.githubusercontent.com/11908261/42413952-1a63f046-8234-11e8-9b7e-faa12a82a55b.png)

[link for the file I uploaded](https://void.cat/ba084d3f143f2896809d3f1d7dffed472b39d8de)

verified the test by using two different computers.

**Comment by v0l** [comment]
That file empty which means the upload failed to apply, im checking it now.

**Comment by 3k2** [comment]
I also  tested with a file that contains a video about size of 5gb it gave me same result wants to download beamNG.mp4

**Comment by v0l** [comment]
https://github.com/v0l/void.cat/commit/2457db5face5b0175dffa7982081e15d1430dacd
