### ISSUE TITLE
Encryption crashes on v3

### ISSUE THREAD

**Issue by chocolatkey** [v0l/void.cat#18]
I am trying to upload a 348MB file, and the encryption stage of the upload crashes in Chrome (latest version). Works in Firefox
Additionally, the post request is going through cloudflare, and with cloudflare, you cannot advertise the 8GiB max due to their upload size limits. Server will respond with 412 entity too large
![image](https://user-images.githubusercontent.com/13407784/48983228-ec9dd380-f0a0-11e8-8145-e3f8b0821e27.png)

**Comment by v0l** [comment]
Yea if you need to upload anything larger than 100MiB then you should use Firefox its not crashing.

Im also going to provide command line tools for uploading.

Uploads shouldnt be going through CF anymore try to clear you cache. last commit this was changed.

**Comment by v0l** [comment]
On further investigation this is due to some missing config in redis, please check this again it should be working now.
