### ISSUE TITLE
Doesn't work in Pale Moon

### ISSUE THREAD

**Issue by VegetableJuice** [v0l/void.cat#2]
'Aint working in Pale Moon anymore since the rework.
![2017-11-10_21-08-21_4i23vk62](https://user-images.githubusercontent.com/13252056/32676544-56ebefe0-c65b-11e7-8472-2d206b581ebc.png)

**Comment by v0l** [comment]
#https://github.com/MoonchildProductions/Pale-Moon/issues/1243
