### ISSUE TITLE
[Chrome] TypeError: Cannot read property 'importKey' of undefined

### ISSUE THREAD

**Issue by MrDemocracy** [v0l/void.cat#20]
I get `TypeError: Cannot read property 'importKey' of undefined` when it starts decrypting the file. This only happens when I use Google Chrome.

**Comment by v0l** [comment]
What version of chrome?

**Comment by Kadantte** [comment]
Chrome: Version 73.0.3683.86 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/11579313/54879788-0247bd80-4e35-11e9-82c0-584a60c72ea6.png)

**Comment by v0l** [comment]
I just tested it on that version and its working fine, Please use the site over `https`, `crypto.subtle` isn't available over `http`
