### ISSUE TITLE
Long video file playback not working

### ISSUE THREAD

**Issue by v0l** [v0l/void.cat#26]
Sometimes when watching videos on void.cat they fail to playback.

This appears to be due to a bug in the range request handling.

A range request like so is sent implying that 0 bytes should be returned:
`Range: bytes 999-999`

**Comment by BelkaBoi** [comment]
happens to me too but it's just a 30 second video like
https://void.cat/Nm6SZfoqBEucmLtbweYQ68

**Comment by v0l** [comment]
Fixed in 28910368e3ba6794dbb2aa495cca3c3fad8d9fda
