### ISSUE TITLE
CORS issue while calling upload API

### ISSUE THREAD

**Issue by apurvns** [v0l/void.cat#59]
![image](https://user-images.githubusercontent.com/94160378/211543623-363e512e-dc9e-444c-8ddc-ef4afdd4a858.png)

**Comment by apurvns** [comment]
Oh Okay. I cloned your snort.social code to host nostr client on bhojpatra.xyz there I got this issue . I tried to use docker image but its not supporting https requests .

**Comment by v0l** [comment]
If you want to test it locally you can add a host entry for `snort.social` to point to localhost and try that, but the port must also be the standard `443` port

**Comment by apurvns** [comment]
okay got it . thanks
